name: Deploy
on:
  push:
    branches:
      - master
env:
  DOCKER_IMAGE: fmscat/mbc-rando
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker Image
        run: docker build -t $DOCKER_IMAGE:latest .

      - name: Push to Docker Hub
        uses: actions-hub/docker@master
        with:
          args: push $DOCKER_IMAGE:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          username: dockerman
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull $DOCKER_IMAGE
            docker-compose up -d

      - name: Notify on Discord (Failure)
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🚨 **Something went wrong while deploying** 🚨
            <https://github.com/${{ github.repository }}/commit/${{ github.sha }}>

      - name: Notify on Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            Deployed successfully
            <https://github.com/${{ github.repository }}/commit/${{ github.sha }}>
