name: Deploy
on:
  push:
    branches:
      - master
      - actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          username: dockerman
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~

            if [ -e mbc-rando ]; then
              cd mbc-rando
            else
              mkdir -p mbc-rando
              cd mbc-rando
              git init
              git remote add origin ${{ github.event.repository.clone_url }}
            fi

            git fetch --depth=1 origin ${{ github.ref }}
            git checkout FETCH_HEAD
            git gc
            git prune

            cd ..
            docker-compose build
            docker-compose up -d
