name: Deploy
on:
  push:
    branches:
      - master
      - docker-push
env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/mbc-rando
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker Image
        run: |
          docker -v
          cd ~
          ls
          pwd
